name: Pull Request
description: Standard PR template for jekyll-theme-nyx

body:
  - type: markdown
    attributes:
      value: |
        ## Nyx Pull Request

        Thanks for contributing. Fill this out so future-you doesn't hate past-you.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What does this PR do?
      placeholder: Short, clear explanation of the change.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Context
      description: Why does this change exist?
      placeholder: Bug, feature request, refactor, cleanup, etc.
    validations:
      required: false

  - type: textarea
    id: changes
    attributes:
      label: Changes Made
      description: List the main changes.
      placeholder: |
        - Added new tab layout
        - Fixed Rouge highlighting
        - Cleaned up SCSS variables
    validations:
      required: true

  - type: checkboxes
    id: type
    attributes:
      label: Type of Change
      options:
        - label: Bug fix
        - label: New feature
        - label: Breaking change
        - label: Refactor / Cleanup
        - label: Docs only

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Code builds without errors
          required: true
        - label: Tested locally with Jekyll
          required: true
        - label: No unnecessary files committed

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Anything reviewers should know?
      placeholder: Edge cases, follow-ups, known issues.
